### ISSUE TITLE
Working, except cannot ping the internet.

### ISSUE THREAD

**Issue by crkinard** [EverSoJoe/docker-dynamic-ipv6#1]
Many thanks for the script first off. Finally came across it after hours of searching how to deal with dynamic ipv6 prefixes.

But I am running into an issue.
I have the script running:
```
sudo python3 ./docker_dynamic_ipv6.py -i eth0 -li
2022-09-07 04:42:13,818 - INFO - Checkinf if 'ip' system utility is installed
2022-09-07 04:42:13,819 - INFO - Getting IPv6 output for global addresses from system
2022-09-07 04:42:13,834 - INFO - Provided supernet is the same as the subnet in the config
```
Then I launch a test container:
`sudo docker run -it --rm busybox`

It gets an ipv6 address:
```
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
18: eth0@if19: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2600:XXXX:XXXX:aa00:8000:XXX:XXXX:X/65 scope global flags 02
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link
       valid_lft forever preferred_lft forever
```
It can resolve:
```
/ # nslookup google.com
Server:         192.168.50.1
Address:        192.168.50.1:53

Non-authoritative answer:
Name:   google.com
Address: 2607:f8b0:4006:81d::200e

*** Can't find google.com: No answer
```
But I cannot ping. Any ideas?

Also two other questions.
- Why does it give a /65 instead of a /64? ISP gives me a /56.
- Modifying daemon.json I think only applies to the default network. Which reading I hear its garbage and should make your own. Not sure how I might get this to apply to a macvlan I make in docker-compose.yml.

**Comment by EverSoJoe** [comment]
Hi!

Did not think anyone would come across this, but thank you for opening this issue. 
I have not tested this myself yet and just wrote this script into the blue. When it comes to your issues and questions:

> I think it is because the subnet is not routed to because the router doesn’t know that it exists. Your docker host needs to advertise it to the network. You can use radvd (router advertisement daemon) for that. Maybe I will integrate that in a future revision

> It gives a subnet based on the docker host’s own ipv6 address, which is in my case a /64. I’m sure you can change that though. I, for my part, don’t mind it

> My experience with docker is very limited, that’s why I wanted to start with a default configuration and my use case is not very demanding, which means I’m fine with not as efficient solutions. But you should be able to adapt this solution to any kind of configuration change

If my solutions don’t work then just get back to me. Hope you find a working solution for you.

**Comment by crkinard** [comment]
Found a fix for the not being able to ping. Yeah it is a routing issue, and it is easy to fix.

Add these to daemon.json
`    "ip6tables": true,
     "experimental": true,`

Seems this will auto add/remove the ip6tables entries needed to make things work.
You need at least docker 20.10.5/docker-compose 1.28.6.

**Comment by crkinard** [comment]
Hummm. Getting a weird thing where for some reason the script picks the link-local address instead of the global one.
```
crkinard@rbpi-01 ~ $ sudo python3 ./docker_dynamic_ipv6.py -i eth0 -li && cat /etc/docker/daemon.json
2022-09-07 16:56:25,647 - INFO - Checkinf if 'ip' system utility is installed
2022-09-07 16:56:25,648 - INFO - Getting IPv6 output for global addresses from system
2022-09-07 16:56:25,663 - INFO - Provided supernet is NOT the same as the subnet in the config
2022-09-07 16:56:25,664 - INFO - Writing new IPv6 prefix to docker config
2022-09-07 16:56:25,666 - INFO - Restarting docker daemon
2022-09-07 16:56:28,584 - INFO - Docker daemon restarted successfully
{
    "experimental": true,
    "fixed-cidr-v6": "fd67:662f:a332:49cb:8000::/65",
    "ip6tables": true,
    "ipv6": true
}
```
Run the script again right after and it picks the proper one, sometimes. Script seems to bounce back and forth between the fXXX... and 2XXX... IP's.

**Comment by EverSoJoe** [comment]
That’s really weird, yeah… The only reason I can see this happening is when
the lease of the ipv6 just ran out or it being a big of the ip utility.
I’ll investigate later.

crkinard ***@***.***> schrieb am Mi. 7. Sept. 2022 um 22:58:

**Comment by crkinard** [comment]
Yeah, getting this every so often.

```
crkinard@rbpi-00:~$ ip -6 -json address show dev eth0 scope global | python3 -mjson.tool
[
    {
        "ifindex": 2,
        "ifname": "eth0",
        "flags": [
            "BROADCAST",
            "MULTICAST",
            "UP",
            "LOWER_UP"
        ],
        "mtu": 1500,
        "qdisc": "fq_codel",
        "operstate": "UP",
        "group": "default",
        "txqlen": 1000,
        "addr_info": [
            {
                "family": "inet6",
                "local": "fd67:662f:a332:49cb:ba27:ebff:fe83:4743",
                "prefixlen": 64,
                "scope": "global",
                "tentative": true,
                "dynamic": true,
                "mngtmpaddr": true,
                "noprefixroute": true,
                "valid_life_time": 1800,
                "preferred_life_time": 1800
            },
            {
                "family": "inet6",
                "local": "2600:XXXX:XXXX:XXXX:ba27:ebff:fe83:4743",
                "prefixlen": 64,
                "scope": "global",
                "dynamic": true,
                "mngtmpaddr": true,
                "noprefixroute": true,
                "valid_life_time": 595,
                "preferred_life_time": 595
            },
            {}
        ]
    }
]
```
Seems like there is a check you can run with python (3.5+) to see if it's a private IP or a global one.

**Comment by EverSoJoe** [comment]
It seems to be a tentative address which is why the link local address is
defined as global for some reason. The ip tool defines it as global, which
is weird. I’ll do a commit soon which checks for tentative and link local
address and waits until the next run if there is one.
Is your address being redefined that often? It only happens every few days
for me.

crkinard ***@***.***> schrieb am Do. 8. Sept. 2022 um 21:52:

**Comment by crkinard** [comment]
IPv4 IP and IPv6 prefix only seem to change when the router/ONT restarts. Sometimes not even then. But it does happen so gotta account for it.

**Comment by EverSoJoe** [comment]
Then it doesn’t make sense that you get a tentative address so often. But
I’ll handle this edge case in the next update

crkinard ***@***.***> schrieb am Do. 8. Sept. 2022 um 22:46:

**Comment by EverSoJoe** [comment]
I just commited a change that checks for tentative and private addresses and skips those. Please check if it fixes anything. I need to look at this further when I have more time, but I think we don't want to use tentative addresses as docker prefix

**Comment by crkinard** [comment]
Works good. Just need to modify it a tad for my situation. I am running docker on 4 pi's so I need a subnet for each pi that is not the same. Best I can figure is just randomizing the subnet.

First, make the subnet a /64 instead of a /65. For some reason the python code increments the subnet by one by default.
Line 49:
`    if docker_ipv6_net.supernet(prefixlen_diff=0) == sys_ipv6_net:`
Line 69:
`    *_, last_subnet = sys_ipv6_net.subnets(prefixlen_diff=0)`

This causes the subnet that is spit out to be the same one the router is using.
Something like : `2600:XXXX:XXXX:200::/64`
Which means the subnet the isp gives is: `2600:XXXX:XXXX:200::/56`

Feed that into the def below and it should spit out a random /64 that docker can now use.

This should work but I have no idea how to implement it in the overall script.
```
from ipaddress import IPv6Network
import random
def random_subnet(isp_subnet):
    subnet = IPv6Network(isp_subnet)
    random_network = IPv6Network((
        subnet.network_address + (random.getrandbits(64 - subnet.prefixlen) << 64 ),
        64))
    return random_network
```

**Comment by EverSoJoe** [comment]
Hi! Sorry for dropping off the face of the earth. If this is still relevant:
The reason why I increment the subnet is just personal preference and readability. The first subnet would just be the same as the hosts just with the CIDR of 65. By incrementing it by one I at least get a different one.

As for how to implement your solution. You just need to replace the subnet that is being placed into the docker config in the function 'update_docker_prefix' with your own and it will be taken care of.

What could be implemented in the case of a cluster is a way to not configure the same address multiple times, but I would need to look into a mechanic myself. Maybe through the neighbor discovery protocol.
